apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cinderschedule
  name: cinderschedule
  namespace: openstack
spec:
  hostNetwork: true
  nodeSelector: 
    controller: "true"
  containers:
  - env:
    - name: controllerIP
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: controllerIP
    image: www.myharbor.com:10443/168447636/deepin20-cinderschedule:20.5
    name: cinderschedule
    ports:
    - containerPort: 8776
      protocol: TCP
    volumeMounts:
    - name: hosts-config
      mountPath: "/depstack/configmap"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: hosts-config
    configMap:
      name: hosts-config

status: {}
