apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: glance
  name: glance
  namespace: openstack
spec:
  hostNetwork: true
  nodeSelector: 
    controller: "true"
  containers:
  - image: www.myharbor.com:10443/168447636/deepin20-glance:20.5
    name: glance
    ports:
    - containerPort: 9191
      protocol: TCP
    - containerPort: 9292
      protocol: TCP
    volumeMounts:
    - name: hosts-config
      mountPath: "/depstack/configmap"
    - name: images-dir
      mountPath: "/var/lib/glance/images"
    resources: {}
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: hosts-config
    configMap:
      name: hosts-config
  - name: images-dir
    hostPath:
      path: /var/lib/glance/images
