apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nova
  name: nova
  namespace: openstack
spec:
  hostNetwork: true
  nodeSelector: 
    controller: "true"
  containers:
  - env:
    - name: controllerIP
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: controllerIP
    - name: virt_type
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: virt_type
    image: www.myharbor.com:10443/168447636/deepin20-nova:20.5
    name: nova
    ports:
    - containerPort: 8774
      protocol: TCP
    - containerPort: 8775
      protocol: TCP
    - containerPort: 8778
      protocol: TCP
    - containerPort: 6082
      protocol: TCP
    - containerPort: 6083
      protocol: TCP
    volumeMounts:
    - name: hosts-config
      mountPath: "/depstack/configmap"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: hosts-config
    configMap:
      name: hosts-config

status: {}

