apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
  namespace: openstack
spec:
  hostNetwork: true
  nodeSelector: 
    controller: "true"
  containers:
  - env:
    - name: RABBITMQ_DEFAULT_USER
      value: uosrabbitmq
    - name: RABBITMQ_DEFAULT_PASS
      value: rabbitmq
    image: www.myharbor.com:10443/168447636/rabbitmq:3-management
    name: rabbitmq
    ports:
    - containerPort: 5672
      protocol: TCP
    - containerPort: 15672
      protocol: TCP
    volumeMounts:
    - name: datadir
      mountPath: "/var/lib/rabbitmq"
  restartPolicy: Always
  volumes:
  - name: datadir
    hostPath: 
      path: /var/lib/rabbitmq
